# Generated by Django 2.2.4 on 2019-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
